# Generated by Django 5.1.7 on 2025-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='LH',
        ),
        migrations.AlterModelOptions(
            name='hp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lhp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ls',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nh',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taikhoan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ttdk',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ttht',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ttns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ttsv',
            options={'managed': True},
        ),
    ]
